In [ ]:
import numpy as np

In [ ]:
# Identity Matrix
var = np.eye(3)
display(var)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((3,3))


array([[0.69668318, 0.50722961, 0.14464673],
       [0.96847715, 0.91144547, 0.55936416],
       [0.91364523, 0.43156322, 0.03930718]])

In [ ]:
display(var.shape)

(3, 3)

In [ ]:
display(var.dtype)

dtype('float64')

In [ ]:
display(var.size)

9

In [ ]:
display(var.ndim)

2

In [ ]:
one_mat = np.ones((3,5,5))

In [ ]:
display(one_mat)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
display(one_mat.ndim)

3

In [ ]:
np.random.randint(10,size=(4,4))

array([[2, 1, 1, 8],
       [2, 5, 1, 1],
       [4, 0, 7, 3],
       [8, 4, 9, 7]])

**Indexing of Arrays**

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(20)**2

In [ ]:
display(a)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
a[0:-1]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324])

In [ ]:
a[-5:]

array([225, 256, 289, 324, 361])

**Vector Operations**

In [ ]:
val1= np.arange(6).reshape(1,6)

In [ ]:
val2 = np.arange(6).reshape(6,1)

In [ ]:
np.dot(val1,val2)

array([[55]])

**Elementwise Dot Product**

In [ ]:
x = np.arange(6).reshape(1,6)
w = np.arange(6).reshape(6,1)

np.multiply(x,w)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20],
       [ 0,  5, 10, 15, 20, 25]])

In [ ]:
x

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
w

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.nan

nan

In [ ]:
import pandas as pd

In [ ]:
data_series = {'Column1' : pd.Series(data = [100, 200, 300, 400, 500], index=['a', 'b', 'c', 'd', 'f']), 
               'Column2' : pd.Series(data = [10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])}

In [ ]:
pd.DataFrame(data_series)

Column1  Column2
a    100.0     10.0
b    200.0     20.0
c    300.0     30.0
d    400.0     40.0
e      NaN     50.0
f    500.0      NaN

In [ ]:
matrix_1 = np.random.randint(100, size = (3,3,3))

In [ ]:
display(matrix_1)

array([[[29, 85, 86],
        [97, 84, 75],
        [67, 58,  3]],

       [[97,  3, 37],
        [53, 92, 28],
        [59, 58, 31]],

       [[61, 87, 49],
        [ 6, 78, 36],
        [48, 35, 99]]])

In [ ]:
matrix_1[2][0][0]

61